version: '3.4'
services:
  redis:
    container_name: 'redis-server'
    image: 'redis'
    ports:
      - "6379:6379"
  backend:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    ports:
      - "8080:8080"
    depends_on:
      - redis
    volumes:
      - ../care-home.pem:/app/keys/care-home.pem
    image: softmakersdev029/care-home-backend:latest
  frontend:
    build:
      context: ../../../workspace_frontend/care-home-typed
      dockerfile: Dockerfile.production
    ports:
      - "5176:80"
    depends_on:
      - backend
    image: softmakersdev029/care-home-frontend:latest
