version: '3.4'
services:
  redis:
    container_name: 'redis-server'
    image: 'redis'
    ports:
      - "6379:6379"
  backend:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
      - "5005:5005" # FOR DEBUGGING
    depends_on:
      - redis
    volumes:
      - ../care-home.pem:/app/keys/care-home.pem
  frontend:
    build:
      context: /Users/michaelkim/workspace_frontend/care-home-typed
      dockerfile: /Users/michaelkim/workspace_frontend/care-home-typed/Dockerfile.dev
    volumes:
      - /Users/michaelkim/workspace_frontend/care-home-typed:/app
      - /app/node-modules
    ports:
      - "5176:5176"
    depends_on:
      - backend
