################# Authentication ##################
server-domain=ec2-3-38-167-207.ap-northeast-2.compute.amazonaws.com

##################### API url #####################
api-frontend-main-url=http://ec2-3-38-167-207.ap-northeast-2.compute.amazonaws.com:5176
