################# Authentication ##################
server-domain=ec2-16-184-12-151.ap-northeast-2.compute.amazonaws.com

##################### API url #####################
api-frontend-main-url=http://ec2-16-184-12-151.ap-northeast-2.compute.amazonaws.com:5176
